//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.07 at 02:55:51 PM ICT 
//


package com.dvm.soap_service.endpoint.dto;

import javax.xml.bind.annotation.*;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dvm.soap_service.endpoint.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dvm.soap_service.endpoint.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XacThucThongTinCongDanRequest }
     * 
     */
    public XacThucThongTinCongDanRequest createXacThucThongTinCongDanRequest() {
        return new XacThucThongTinCongDanRequest();
    }

    /**
     * Create an instance of {@link XacThucThongTinCongDanResponse }
     * 
     */
    public XacThucThongTinCongDanResponse createXacThucThongTinCongDanResponse() {
        return new XacThucThongTinCongDanResponse();
    }

    /**
     * Create an instance of {@link XacThucThongTinCongDan }
     * 
     */
    public XacThucThongTinCongDan createXacThucThongTinCongDan() {
        return new XacThucThongTinCongDan();
    }

    /**
     * Create an instance of {@link KetQuaXacThuc }
     * 
     */
    public KetQuaXacThuc createKetQuaXacThuc() {
        return new KetQuaXacThuc();
    }

}
