//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.07 at 02:55:51 PM ICT 
//

@XmlSchema(namespace = "http://dancuquocgia.bca",
        elementFormDefault = XmlNsForm.QUALIFIED)
package com.dvm.soap_service.endpoint.dto;

import javax.xml.bind.annotation.*;