//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.06 at 07:08:34 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://dancuquocgia.bca", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dvm.soap_service.endpoint.dto;
