//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.07 at 04:36:17 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.demo.example.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dvm.soap_service.endpoint.dto;
