//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.07 at 02:55:51 PM ICT 
//


package com.dvm.soap_service.endpoint.dto;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MaYeuCau" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MaDichVu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MaCanBo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SoDinhDanh" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SoCMND" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HoVaTen" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maYeuCau",
    "maDichVu",
    "maCanBo",
    "soDinhDanh",
    "soCMND",
    "hoVaTen"
})
@XmlRootElement(name = "XacThucThongTinCongDanRequest")
public class XacThucThongTinCongDanRequest {

    @XmlElement(name = "MaYeuCau", required = true)
    protected String maYeuCau;
    @XmlElement(name = "MaDichVu", required = true)
    protected String maDichVu;
    @XmlElement(name = "MaCanBo", required = true)
    protected String maCanBo;
    @XmlElement(name = "SoDinhDanh", required = true)
    protected String soDinhDanh;
    @XmlElement(name = "SoCMND", required = true)
    protected String soCMND;
    @XmlElement(name = "HoVaTen", required = true)
    protected String hoVaTen;

    /**
     * Gets the value of the maYeuCau property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaYeuCau() {
        return maYeuCau;
    }

    /**
     * Sets the value of the maYeuCau property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaYeuCau(String value) {
        this.maYeuCau = value;
    }

    /**
     * Gets the value of the maDichVu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaDichVu() {
        return maDichVu;
    }

    /**
     * Sets the value of the maDichVu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaDichVu(String value) {
        this.maDichVu = value;
    }

    /**
     * Gets the value of the maCanBo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaCanBo() {
        return maCanBo;
    }

    /**
     * Sets the value of the maCanBo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaCanBo(String value) {
        this.maCanBo = value;
    }

    /**
     * Gets the value of the soDinhDanh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoDinhDanh() {
        return soDinhDanh;
    }

    /**
     * Sets the value of the soDinhDanh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoDinhDanh(String value) {
        this.soDinhDanh = value;
    }

    /**
     * Gets the value of the soCMND property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoCMND() {
        return soCMND;
    }

    /**
     * Sets the value of the soCMND property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoCMND(String value) {
        this.soCMND = value;
    }

    /**
     * Gets the value of the hoVaTen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoVaTen() {
        return hoVaTen;
    }

    /**
     * Sets the value of the hoVaTen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoVaTen(String value) {
        this.hoVaTen = value;
    }

}
