//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.07 at 03:56:41 PM ICT 
//

@XmlSchema(namespace = "http://spring.io/guides/gs-producing-web-service",
        elementFormDefault = XmlNsForm.QUALIFIED)
package com.dvm.soap_service.dto;


import javax.xml.bind.annotation.*;